[package]
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2018"
name = "oled_actor"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
oled-ssd1306-interface = {path = "../oled_ssd1306/oled-ssd1306-interface"}
wapc-guest = "0.4.0"
wasmcloud-actor-core = {git = "https://github.com/wascc/actor-interfaces", branch = "main", features = ["guest"]}
wasmcloud-actor-http-server = {git = "https://github.com/wascc/actor-interfaces", branch = "main", features = ["guest"]}

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
