apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  strategy: {}
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - args:
            - -js
          image: nats:2.7.1
          name: nats-container
          ports:
            - containerPort: 4222
            - containerPort: 6222
            - containerPort: 8222
          resources:
            limits:
              memory: "200Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "0.5"
          restartPolicy: Always
