apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    app: registry
  type: LoadBalancer
