apiVersion: v1
kind: Service
metadata:
  labels:
    app: wasmcloud
  name: wasmcloud
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
    - name: "443"
      port: 443
      targetPort: 8443
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: wasmcloud
