[package]
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2018"
name = "hello-http"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.59"
wascc-actor = "0.7.1"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
